version: '2.4'

services:
  games:
    image: tsmarsh/games
    restart: unless-stopped
    ports:
      - 80:8888
    environment:
     - DB_NAME=dev
     - DB_ADDRESS=mongodb:27017
  gamescommand:
    image: tsmarsh/gamescommand
    restart: unless-stopped
    ports:
      - 81:8888
    environment:
      - DB_NAME=dev
      - DB_ADDRESS=mongodb:27017
      - PORT=8888
  mongodb:
    image: mongo
    ports:
    - 27017:27017